filter:
    excluded_paths: [vendor/*, tests/*, .php-cs-fixer.php]
checks:
    php:
        code_rating: true
        duplication: true
tools:
    php_code_sniffer:
        config:
            standard: "PSR12"
build:
  nodes:
    analysis:
        dependencies:
            override:
                - composer install --ignore-platform-reqs --no-interaction
        environment:
            php:
                version: 8.1
                ini:
                    xdebug.mode: coverage
        tests:
            override:
                - php-scrutinizer-run
                - command: './vendor/bin/phpunit tests/'
                  coverage:
                    file: build/logs/clover.xml
                    format: clover