filter:
    excluded_paths: [vendor/*, tests/*]
checks:
    php:
        code_rating: true
        duplication: true
tools:
    external_code_coverage:
        timeout: 630
    php_code_sniffer:
        config:
            standard: "PSR2"
