filter:
    excluded_paths: [vendor/*, tests/*]
checks:
    php:
        code_rating: true
        duplication: true
tools:
    php_code_sniffer:
        config:
            standard: "PSR2"
build:
    environment:
        php:
            version: 8.1
    tests:
        override:
            - command: './vendor/bin/phpunit tests/'