language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
install:
  - composer require satooshi/php-coveralls:~0.6@stable
before_script: composer dump-autoload
script:
    - phpunit --configuration code-coverage.xml tests/
after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'
