language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
install:
  - composer require satooshi/php-coveralls:~0.6@stable
before_script: composer dump-autoload
script:
    - phpunit --configuration code-coverage.xml tests/
after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
notifications:
  email: false
